#!/usr/bin/env python3
"""Extract function-level CC/cognitive metrics from rust-code-analysis JSON output.

Usage:
  python3 docs/clean-code-plan/extract-metrics.py

Reads from metrics-output/ (generated by rust-code-analysis-cli) and prints a
sorted table of functions with CC > 5 plus a file-level aggregate table.
"""

import json
import glob
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent.parent  # repo root
METRICS_DIR = ROOT / "metrics-output"


def walk_spaces(spaces, filepath, results):
    for s in spaces or []:
        if s.get("kind") == "function" and "metrics" in s:
            m = s["metrics"]
            results.append(
                {
                    "file": filepath,
                    "name": s.get("name", "?"),
                    "cc": int(m.get("cyclomatic", {}).get("sum", 0)),
                    "cognitive": int(m.get("cognitive", {}).get("sum", 0)),
                    "sloc": int(m.get("loc", {}).get("sloc", 0)),
                }
            )
        walk_spaces(s.get("spaces", []), filepath, results)


def main():
    threshold = int(sys.argv[1]) if len(sys.argv) > 1 else 5

    fn_results = []
    file_cc = {}
    file_cog = {}
    file_sloc = {}

    for jpath in sorted(METRICS_DIR.rglob("*.json")):
        with open(jpath) as f:
            data = json.load(f)

        rel = str(jpath).replace(str(METRICS_DIR) + "/src/", "").replace(".json", "")
        m = data.get("metrics", {})
        cc = int(m.get("cyclomatic", {}).get("sum", 0))
        cog = int(m.get("cognitive", {}).get("sum", 0))
        sloc = int(m.get("loc", {}).get("sloc", 0))
        if cc > 0:
            file_cc[rel] = cc
            file_cog[rel] = cog
            file_sloc[rel] = sloc

        walk_spaces(data.get("spaces", []), rel, fn_results)

    fn_results.sort(key=lambda x: -x["cc"])

    print("\n## Functions with CC > {} (sorted by CC)\n".format(threshold))
    print(f"{'CC':>4}  {'Cog':>4}  {'SLOC':>5}  Name  [File]")
    for r in fn_results:
        if r["cc"] > threshold:
            print(
                f"CC={r['cc']:3d}  Cog={r['cognitive']:3d}  SLOC={r['sloc']:4d}"
                f"  {r['name']}  [{r['file']}]"
            )

    print("\n## Files by aggregate CC\n")
    print(f"{'CC':>5}  {'Cog':>5}  {'SLOC':>5}  File")
    for f, cc in sorted(file_cc.items(), key=lambda x: -x[1]):
        cog = file_cog.get(f, 0)
        sloc = file_sloc.get(f, 0)
        print(f"{cc:5d}  {cog:5d}  {sloc:5d}  {f}")


if __name__ == "__main__":
    main()
